steps:

- id: "Run tests"
  name: 'gcr.io/cloud-builders/go'
  env: ['GOPATH=.']
  args: ['test', 'challenge07', '-v', '-cover']

- id: "Building image from Dockerfile.prod"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go:${SHORT_SHA}', '-f', 'Dockerfile.prod', '.']

- id: "Uploading docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/app-go"]

- id: "Adjusting kubernetes deployment file"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go:$SHORT_SHA#g' \
        k8s/deployment-template.yaml > k8s/deployment.prod.yaml && \
      cat k8s/deployment.prod.yaml
- id: "Deploying application"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/deployment.prod.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'
