apiVersion: v1
kind: Service
metadata:
  name: microservices-devops-challenge07
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: microservices-devops-challenge07
